#!/bin/bash 
 clear
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-0.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-0.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-1.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-1.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-2.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-2.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-3.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-3.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-4.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-4.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-5.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-5.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-6.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-6.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-7.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-7.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-3.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-3.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-8.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-8.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-9.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-9.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-10.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-10.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-11.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-11.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-12.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-12.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-13.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-13.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-14.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-14.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-15.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-15.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-16.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-16.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-17.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-17.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-18.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-18.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-19.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-19.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-20.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-20.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-21.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-21.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-22.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-22.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-23.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-23.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-24.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-24.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-25.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-25.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-26.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-26.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-27.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-27.graph
./mtx2el-graph ~/inputs/mtx_graphs/beam-hex.mesh-M-4-idx-28.mtx ~/inputs/small_mesh_graph/beam-hex.mesh-M-4-idx-28.graph
./mtx2el-graph ~/inputs/mtx_graphs/star.mesh-M-4-idx-0.mtx ~/inputs/small_mesh_graph/star.mesh-M-4-idx-0.graph
./mtx2el-graph ~/inputs/mtx_graphs/star.mesh-M-4-idx-1.mtx ~/inputs/small_mesh_graph/star.mesh-M-4-idx-1.graph
./mtx2el-graph ~/inputs/mtx_graphs/star.mesh-M-4-idx-2.mtx ~/inputs/small_mesh_graph/star.mesh-M-4-idx-2.graph
./mtx2el-graph ~/inputs/mtx_graphs/star.mesh-M-4-idx-3.mtx ~/inputs/small_mesh_graph/star.mesh-M-4-idx-3.graph
./mtx2el-graph ~/inputs/mtx_graphs/star.mesh-M-4-idx-4.mtx ~/inputs/small_mesh_graph/star.mesh-M-4-idx-4.graph
./mtx2el-graph ~/inputs/mtx_graphs/star.mesh-M-4-idx-5.mtx ~/inputs/small_mesh_graph/star.mesh-M-4-idx-5.graph
./mtx2el-graph ~/inputs/mtx_graphs/star.mesh-M-4-idx-6.mtx ~/inputs/small_mesh_graph/star.mesh-M-4-idx-6.graph
./mtx2el-graph ~/inputs/mtx_graphs/star.mesh-M-4-idx-7.mtx ~/inputs/small_mesh_graph/star.mesh-M-4-idx-7.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-0.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-0.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-10.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-10.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-11.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-11.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-12.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-12.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-13.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-13.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-14.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-14.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-15.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-15.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-16.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-16.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-17.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-17.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-18.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-18.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-19.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-19.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-1.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-1.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-20.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-20.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-21.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-21.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-22.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-22.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-23.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-23.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-24.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-24.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-25.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-25.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-26.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-26.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-27.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-27.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-28.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-28.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-29.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-29.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-2.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-2.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-30.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-30.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-31.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-31.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-3.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-3.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-4.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-4.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-5.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-5.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-6.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-6.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-7.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-7.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-8.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-8.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-9.mtx ~/inputs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-9.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-0.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-0.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-10.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-10.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-11.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-11.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-12.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-12.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-13.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-13.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-14.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-14.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-15.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-15.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-16.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-16.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-17.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-17.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-18.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-18.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-19.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-19.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-1.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-1.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-20.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-20.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-21.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-21.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-22.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-22.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-23.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-23.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-24.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-24.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-25.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-25.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-26.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-26.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-27.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-27.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-28.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-28.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-29.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-29.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-2.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-2.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-30.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-30.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-31.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-31.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-3.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-3.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-4.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-4.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-5.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-5.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-6.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-6.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-7.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-7.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-8.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-8.graph
./mtx2el-graph ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-9.mtx ~/inputs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-9.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-0.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-0.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-1.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-1.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-2.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-2.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-3.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-3.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-4.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-4.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-5.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-5.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-6.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-6.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-7.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-7.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-8.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-8.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-9.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-9.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-10.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-10.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-11.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-11.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-12.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-12.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-13.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-13.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-14.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-14.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-15.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-15.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-16.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-16.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-17.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-17.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-18.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-18.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-19.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-19.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-20.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-20.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-21.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-21.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-22.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-22.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-23.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-23.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-24.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-24.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-25.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-25.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-26.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-26.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-27.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-27.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-28.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-28.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-29.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-29.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-30.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-30.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-31.mtx ~/inputs/small_mesh_graph/toroid-hex.mesh-M-4-idx-31.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-0.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-0.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-1.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-1.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-2.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-2.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-3.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-3.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-4.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-4.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-5.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-5.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-6.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-6.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-7.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-7.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-8.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-8.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-9.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-9.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-10.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-10.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-11.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-11.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-12.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-12.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-13.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-13.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-14.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-14.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-15.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-15.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-16.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-16.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-17.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-17.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-18.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-18.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-19.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-19.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-20.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-20.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-21.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-21.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-22.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-22.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-23.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-23.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-24.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-24.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-25.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-25.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-26.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-26.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-27.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-27.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-28.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-28.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-29.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-29.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-30.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-30.graph
./mtx2el-graph ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-31.mtx ~/inputs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-31.graph
exit 0

