#!/bin/bash 
 clear
cd ~/codes/ECL_SCC
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-0.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-1.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-2.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-3.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-4.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-5.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-6.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-7.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-3.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-8.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-9.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-10.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-11.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-12.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-13.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-14.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-15.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-16.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-17.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-18.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-19.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-20.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-21.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-22.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-23.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-24.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-25.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-26.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-27.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-28.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/star.mesh-M-4-idx-0.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/star.mesh-M-4-idx-1.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/star.mesh-M-4-idx-2.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/star.mesh-M-4-idx-3.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/star.mesh-M-4-idx-4.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/star.mesh-M-4-idx-5.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/star.mesh-M-4-idx-6.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/star.mesh-M-4-idx-7.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-0.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-10.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-11.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-12.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-13.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-14.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-15.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-16.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-17.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-18.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-19.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-1.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-20.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-21.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-22.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-23.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-24.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-25.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-26.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-27.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-28.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-29.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-2.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-30.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-31.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-3.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-4.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-5.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-6.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-7.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-8.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-9.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-0.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-10.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-11.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-12.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-13.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-14.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-15.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-16.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-17.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-18.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-19.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-1.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-20.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-21.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-22.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-23.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-24.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-25.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-26.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-27.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-28.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-29.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-2.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-30.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-31.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-3.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-4.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-5.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-6.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-7.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-8.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-9.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-0.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-1.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-2.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-3.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-4.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-5.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-6.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-7.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-8.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-9.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-10.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-11.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-12.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-13.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-14.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-15.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-16.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-17.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-18.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-19.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-20.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-21.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-22.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-23.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-24.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-25.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-26.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-27.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-28.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-29.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-30.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-31.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-0.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-1.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-2.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-3.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-4.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-5.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-6.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-7.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-8.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-9.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-10.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-11.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-12.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-13.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-14.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-15.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-16.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-17.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-18.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-19.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-20.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-21.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-22.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-23.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-24.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-25.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-26.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-27.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-28.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-29.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-30.egr
./ECL_SCC ~/inputs/ECL_graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-31.egr
exit 0

