#!/bin/bash 
 clear
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-0.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-1.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-10.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-11.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-12.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-13.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-14.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-15.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-16.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-17.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-18.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-19.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-2.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-20.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-21.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-22.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-23.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-24.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-25.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-26.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-27.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-28.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-29.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-3.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-30.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-31.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-4.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-5.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-6.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-7.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-8.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-sponge-tao4-r2.msh-M-4-idx-9.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-0.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-1.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-10.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-11.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-12.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-13.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-14.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-15.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-16.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-17.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-18.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-19.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-2.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-20.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-21.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-22.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-23.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-24.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-25.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-26.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-27.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-28.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-29.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-3.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-30.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-31.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-4.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-5.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-6.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-7.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-8.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/cold-flow-spongezone3.c1.msh-M-4-idx-9.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/klein-bottle.mesh-M-4-idx-0.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/klein-bottle.mesh-M-4-idx-1.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/klein-bottle.mesh-M-4-idx-2.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/klein-bottle.mesh-M-4-idx-3.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/klein-bottle.mesh-M-4-idx-4.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/klein-bottle.mesh-M-4-idx-5.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/klein-bottle.mesh-M-4-idx-6.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/klein-bottle.mesh-M-4-idx-7.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/mobius-strip.mesh-M-4-idx-0.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/mobius-strip.mesh-M-4-idx-1.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/mobius-strip.mesh-M-4-idx-2.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/mobius-strip.mesh-M-4-idx-3.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/mobius-strip.mesh-M-4-idx-4.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/mobius-strip.mesh-M-4-idx-5.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/mobius-strip.mesh-M-4-idx-6.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/mobius-strip.mesh-M-4-idx-7.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-0.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-1.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-10.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-11.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-12.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-13.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-14.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-15.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-16.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-17.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-18.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-19.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-2.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-20.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-21.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-22.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-23.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-24.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-25.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-26.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-27.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-28.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-29.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-3.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-30.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-31.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-4.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-5.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-6.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-7.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-8.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-hex.mesh-M-4-idx-9.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-0.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-1.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-10.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-11.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-12.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-13.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-14.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-15.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-16.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-17.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-18.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-19.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-2.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-20.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-21.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-22.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-23.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-24.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-25.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-26.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-27.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-28.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-29.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-3.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-30.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-31.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-4.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-5.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-6.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-7.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-8.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/toroid-wedge.mesh-M-4-idx-9.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-0.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-1.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-10.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-11.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-12.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-13.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-14.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-15.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-16.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-17.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-18.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-19.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-2.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-20.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-21.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-22.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-23.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-24.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-25.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-26.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-27.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-28.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-3.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-4.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-5.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-6.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-7.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-8.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s3-r4-p.mesh-M-4-idx-9.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-0.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-1.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-10.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-11.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-12.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-13.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-14.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-15.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-16.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-17.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-18.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-19.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-2.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-20.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-21.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-22.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-23.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-24.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-25.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-26.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-27.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-28.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-29.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-3.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-30.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-31.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-4.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-5.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-6.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-7.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-8.egr
wget -P ~/SCC/inputs/ECL_graphs/small_mesh_graphs https://userweb.cs.txstate.edu/~burtscher/research/ECL-SCC/inputs/small-meshes/twist-hex-o3-s6-r4-p.mesh-M-4-idx-9.egr
exit 0

