#!/bin/bash 
clear
cd ~/codes/gpuscc_code
echo -e "input:beam-hex.mesh-M-4-idx-0\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-0.graph
echo -e "input:beam-hex.mesh-M-4-idx-1\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-1.graph
echo -e "input:beam-hex.mesh-M-4-idx-2\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-2.graph
echo -e "input:beam-hex.mesh-M-4-idx-3\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-3.graph
echo -e "input:beam-hex.mesh-M-4-idx-4\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-4.graph
echo -e "input:beam-hex.mesh-M-4-idx-5\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-5.graph
echo -e "input:beam-hex.mesh-M-4-idx-6\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-6.graph
echo -e "input:beam-hex.mesh-M-4-idx-7\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-7.graph
echo -e "input:beam-hex.mesh-M-4-idx-3\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-3.graph
echo -e "input:beam-hex.mesh-M-4-idx-8\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-8.graph
echo -e "input:beam-hex.mesh-M-4-idx-9\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-9.graph
echo -e "input:beam-hex.mesh-M-4-idx-10\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-10.graph
echo -e "input:beam-hex.mesh-M-4-idx-11\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-11.graph
echo -e "input:beam-hex.mesh-M-4-idx-12\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-12.graph
echo -e "input:beam-hex.mesh-M-4-idx-13\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-13.graph
echo -e "input:beam-hex.mesh-M-4-idx-14\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-14.graph
echo -e "input:beam-hex.mesh-M-4-idx-15\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-15.graph
echo -e "input:beam-hex.mesh-M-4-idx-16\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-16.graph
echo -e "input:beam-hex.mesh-M-4-idx-17\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-17.graph
echo -e "input:beam-hex.mesh-M-4-idx-18\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-18.graph
echo -e "input:beam-hex.mesh-M-4-idx-19\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-19.graph
echo -e "input:beam-hex.mesh-M-4-idx-20\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-20.graph
echo -e "input:beam-hex.mesh-M-4-idx-21\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-21.graph
echo -e "input:beam-hex.mesh-M-4-idx-22\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-22.graph
echo -e "input:beam-hex.mesh-M-4-idx-23\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-23.graph
echo -e "input:beam-hex.mesh-M-4-idx-24\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-24.graph
echo -e "input:beam-hex.mesh-M-4-idx-25\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-25.graph
echo -e "input:beam-hex.mesh-M-4-idx-26\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-26.graph
echo -e "input:beam-hex.mesh-M-4-idx-27\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-27.graph
echo -e "input:beam-hex.mesh-M-4-idx-28\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/beam-hex.mesh-M-4-idx-28.graph
echo -e "input:star.mesh-M-4-idx-0\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/star.mesh-M-4-idx-0.graph
echo -e "input:star.mesh-M-4-idx-1\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/star.mesh-M-4-idx-1.graph
echo -e "input:star.mesh-M-4-idx-2\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/star.mesh-M-4-idx-2.graph
echo -e "input:star.mesh-M-4-idx-3\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/star.mesh-M-4-idx-3.graph
echo -e "input:star.mesh-M-4-idx-4\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/star.mesh-M-4-idx-4.graph
echo -e "input:star.mesh-M-4-idx-5\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/star.mesh-M-4-idx-5.graph
echo -e "input:star.mesh-M-4-idx-6\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/star.mesh-M-4-idx-6.graph
echo -e "input:star.mesh-M-4-idx-7\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/star.mesh-M-4-idx-7.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-0\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-0.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-10\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-10.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-11\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-11.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-12\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-12.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-13\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-13.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-14\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-14.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-15\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-15.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-16\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-16.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-17\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-17.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-18\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-18.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-19\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-19.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-1\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-1.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-20\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-20.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-21\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-21.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-22\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-22.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-23\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-23.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-24\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-24.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-25\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-25.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-26\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-26.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-27\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-27.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-28\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-28.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-29\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-29.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-2\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-2.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-30\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-30.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-31\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-31.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-3\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-3.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-4\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-4.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-5\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-5.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-6\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-6.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-7\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-7.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-8\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-8.graph
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-9\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-9.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-0\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-0.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-10\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-10.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-11\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-11.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-12\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-12.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-13\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-13.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-14\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-14.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-15\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-15.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-16\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-16.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-17\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-17.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-18\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-18.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-19\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-19.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-1\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-1.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-20\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-20.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-21\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-21.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-22\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-22.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-23\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-23.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-24\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-24.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-25\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-25.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-26\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-26.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-27\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-27.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-28\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-28.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-29\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-29.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-2\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-2.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-30\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-30.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-31\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-31.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-3\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-3.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-4\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-4.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-5\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-5.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-6\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-6.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-7\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-7.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-8\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-8.graph
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-9\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-9.graph
echo -e "input:toroid-hex.mesh-M-4-idx-0\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-0.graph
echo -e "input:toroid-hex.mesh-M-4-idx-1\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-1.graph
echo -e "input:toroid-hex.mesh-M-4-idx-2\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-2.graph
echo -e "input:toroid-hex.mesh-M-4-idx-3\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-3.graph
echo -e "input:toroid-hex.mesh-M-4-idx-4\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-4.graph
echo -e "input:toroid-hex.mesh-M-4-idx-5\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-5.graph
echo -e "input:toroid-hex.mesh-M-4-idx-6\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-6.graph
echo -e "input:toroid-hex.mesh-M-4-idx-7\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-7.graph
echo -e "input:toroid-hex.mesh-M-4-idx-8\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-8.graph
echo -e "input:toroid-hex.mesh-M-4-idx-9\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-9.graph
echo -e "input:toroid-hex.mesh-M-4-idx-10\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-10.graph
echo -e "input:toroid-hex.mesh-M-4-idx-11\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-11.graph
echo -e "input:toroid-hex.mesh-M-4-idx-12\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-12.graph
echo -e "input:toroid-hex.mesh-M-4-idx-13\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-13.graph
echo -e "input:toroid-hex.mesh-M-4-idx-14\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-14.graph
echo -e "input:toroid-hex.mesh-M-4-idx-15\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-15.graph
echo -e "input:toroid-hex.mesh-M-4-idx-16\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-16.graph
echo -e "input:toroid-hex.mesh-M-4-idx-17\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-17.graph
echo -e "input:toroid-hex.mesh-M-4-idx-18\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-18.graph
echo -e "input:toroid-hex.mesh-M-4-idx-19\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-19.graph
echo -e "input:toroid-hex.mesh-M-4-idx-20\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-20.graph
echo -e "input:toroid-hex.mesh-M-4-idx-21\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-21.graph
echo -e "input:toroid-hex.mesh-M-4-idx-22\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-22.graph
echo -e "input:toroid-hex.mesh-M-4-idx-23\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-23.graph
echo -e "input:toroid-hex.mesh-M-4-idx-24\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-24.graph
echo -e "input:toroid-hex.mesh-M-4-idx-25\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-25.graph
echo -e "input:toroid-hex.mesh-M-4-idx-26\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-26.graph
echo -e "input:toroid-hex.mesh-M-4-idx-27\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-27.graph
echo -e "input:toroid-hex.mesh-M-4-idx-28\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-28.graph
echo -e "input:toroid-hex.mesh-M-4-idx-29\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-29.graph
echo -e "input:toroid-hex.mesh-M-4-idx-30\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-30.graph
echo -e "input:toroid-hex.mesh-M-4-idx-31\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-hex.mesh-M-4-idx-31.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-0\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-0.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-1\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-1.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-2\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-2.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-3\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-3.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-4\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-4.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-5\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-5.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-6\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-6.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-7\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-7.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-8\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-8.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-9\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-9.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-10\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-10.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-11\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-11.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-12\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-12.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-13\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-13.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-14\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-14.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-15\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-15.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-16\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-16.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-17\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-17.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-18\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-18.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-19\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-19.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-20\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-20.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-21\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-21.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-22\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-22.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-23\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-23.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-24\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-24.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-25\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-25.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-26\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-26.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-27\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-27.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-28\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-28.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-29\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-29.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-30\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-30.graph
echo -e "input:toroid-wedge.mesh-M-4-idx-31\n"
./scc_2_w -f ~/inputs/GPU_SCC_Graphs/small_mesh_graphs/toroid-wedge.mesh-M-4-idx-31.graph
exit 0