#!/bin/bash 
 clear

cd ~/codes/iSpan/src

echo -e "input:beam-hex.mesh-M-4-idx-0\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-0.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-0.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-0.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-0.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-1\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-1.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-1.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-1.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-1.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-2\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-2.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-2.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-2.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-2.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-3\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-3.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-3.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-3.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-3.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-4\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-4.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-4.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-4.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-4.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-5\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-5.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-5.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-5.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-5.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-6\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-6.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-6.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-6.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-6.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-7\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-7.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-7.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-7.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-7.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-3\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-3.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-3.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-3.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-3.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-8\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-8.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-8.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-8.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-8.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-9\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-9.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-9.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-9.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-9.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-10\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-10.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-10.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-10.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-10.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-11\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-11.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-11.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-11.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-11.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-12\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-12.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-12.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-12.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-12.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-13\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-13.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-13.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-13.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-13.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-14\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-14.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-14.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-14.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-14.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-15\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-15.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-15.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-15.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-15.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-16\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-16.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-16.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-16.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-16.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-17\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-17.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-17.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-17.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-17.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-18\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-18.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-18.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-18.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-18.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-19\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-19.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-19.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-19.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-19.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-20\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-20.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-20.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-20.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-20.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-21\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-21.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-21.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-21.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-21.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-22\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-22.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-22.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-22.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-22.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-23\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-23.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-23.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-23.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-23.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-24\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-24.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-24.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-24.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-24.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-25\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-25.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-25.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-25.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-25.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-26\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-26.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-26.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-26.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-26.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-27\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-27.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-27.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-27.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-27.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:beam-hex.mesh-M-4-idx-28\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-28.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-28.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-28.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-28.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:star.mesh-M-4-idx-0\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-0.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-0.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-0.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-0.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:star.mesh-M-4-idx-1\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-1.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-1.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-1.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-1.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:star.mesh-M-4-idx-2\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-2.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-2.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-2.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-2.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:star.mesh-M-4-idx-3\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-3.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-3.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-3.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-3.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:star.mesh-M-4-idx-4\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-4.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-4.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-4.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-4.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:star.mesh-M-4-idx-5\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-5.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-5.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-5.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-5.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:star.mesh-M-4-idx-6\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-6.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-6.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-6.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-6.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:star.mesh-M-4-idx-7\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-7.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-7.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-7.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-7.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-0\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-0.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-0.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-0.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-0.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-10\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-10.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-10.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-10.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-10.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-11\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-11.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-11.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-11.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-11.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-12\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-12.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-12.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-12.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-12.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-13\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-13.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-13.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-13.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-13.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-14\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-14.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-14.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-14.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-14.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-15\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-15.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-15.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-15.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-15.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-16\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-16.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-16.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-16.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-16.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-17\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-17.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-17.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-17.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-17.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-18\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-18.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-18.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-18.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-18.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-19\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-19.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-19.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-19.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-19.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-1\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-1.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-1.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-1.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-1.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-20\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-20.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-20.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-20.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-20.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-21\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-21.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-21.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-21.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-21.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-22\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-22.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-22.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-22.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-22.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-23\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-23.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-23.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-23.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-23.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-24\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-24.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-24.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-24.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-24.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-25\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-25.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-25.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-25.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-25.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-26\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-26.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-26.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-26.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-26.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-27\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-27.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-27.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-27.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-27.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-28\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-28.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-28.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-28.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-28.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-29\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-29.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-29.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-29.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-29.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-2\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-2.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-2.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-2.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-2.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-30\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-30.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-30.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-30.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-30.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-31\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-31.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-31.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-31.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-31.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-3\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-3.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-3.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-3.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-3.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-4\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-4.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-4.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-4.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-4.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-5\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-5.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-5.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-5.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-5.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-6\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-6.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-6.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-6.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-6.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-7\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-7.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-7.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-7.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-7.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-8\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-8.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-8.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-8.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-8.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-sponge-tao4-r2.msh-M-4-idx-9\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-9.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-9.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-9.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-9.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-0\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-0.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-0.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-0.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-0.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-10\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-10.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-10.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-10.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-10.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-11\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-11.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-11.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-11.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-11.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-12\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-12.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-12.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-12.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-12.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-13\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-13.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-13.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-13.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-13.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-14\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-14.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-14.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-14.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-14.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-15\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-15.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-15.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-15.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-15.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-16\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-16.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-16.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-16.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-16.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-17\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-17.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-17.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-17.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-17.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-18\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-18.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-18.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-18.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-18.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-19\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-19.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-19.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-19.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-19.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-1\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-1.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-1.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-1.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-1.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-20\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-20.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-20.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-20.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-20.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-21\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-21.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-21.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-21.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-21.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-22\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-22.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-22.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-22.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-22.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-23\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-23.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-23.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-23.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-23.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-24\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-24.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-24.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-24.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-24.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-25\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-25.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-25.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-25.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-25.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-26\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-26.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-26.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-26.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-26.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-27\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-27.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-27.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-27.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-27.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-28\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-28.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-28.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-28.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-28.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-29\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-29.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-29.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-29.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-29.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-2\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-2.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-2.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-2.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-2.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-30\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-30.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-30.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-30.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-30.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-31\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-31.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-31.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-31.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-31.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-3\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-3.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-3.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-3.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-3.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-4\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-4.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-4.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-4.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-4.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-5\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-5.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-5.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-5.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-5.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-6\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-6.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-6.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-6.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-6.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-7\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-7.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-7.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-7.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-7.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-8\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-8.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-8.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-8.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-8.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:cold-flow-spongezone3.c1.msh-M-4-idx-9\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-9.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-9.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-9.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-9.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-0\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-0.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-0.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-0.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-0.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-1\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-1.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-1.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-1.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-1.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-2\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-2.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-2.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-2.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-2.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-3\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-3.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-3.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-3.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-3.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-4\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-4.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-4.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-4.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-4.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-5\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-5.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-5.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-5.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-5.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-6\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-6.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-6.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-6.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-6.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-7\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-7.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-7.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-7.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-7.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-8\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-8.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-8.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-8.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-8.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-9\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-9.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-9.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-9.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-9.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-10\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-10.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-10.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-10.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-10.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-11\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-11.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-11.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-11.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-11.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-12\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-12.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-12.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-12.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-12.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-13\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-13.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-13.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-13.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-13.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-14\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-14.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-14.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-14.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-14.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-15\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-15.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-15.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-15.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-15.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-16\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-16.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-16.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-16.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-16.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-17\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-17.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-17.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-17.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-17.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-18\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-18.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-18.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-18.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-18.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-19\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-19.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-19.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-19.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-19.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-20\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-20.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-20.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-20.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-20.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-21\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-21.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-21.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-21.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-21.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-22\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-22.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-22.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-22.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-22.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-23\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-23.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-23.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-23.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-23.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-24\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-24.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-24.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-24.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-24.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-25\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-25.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-25.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-25.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-25.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-26\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-26.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-26.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-26.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-26.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-27\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-27.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-27.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-27.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-27.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-28\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-28.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-28.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-28.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-28.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-29\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-29.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-29.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-29.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-29.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-30\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-30.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-30.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-30.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-30.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-hex.mesh-M-4-idx-31\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-31.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-31.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-31.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-31.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-0\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-0.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-0.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-0.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-0.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-1\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-1.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-1.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-1.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-1.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-2\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-2.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-2.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-2.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-2.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-3\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-3.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-3.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-3.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-3.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-4\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-4.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-4.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-4.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-4.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-5\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-5.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-5.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-5.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-5.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-6\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-6.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-6.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-6.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-6.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-7\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-7.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-7.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-7.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-7.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-8\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-8.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-8.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-8.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-8.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-9\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-9.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-9.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-9.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-9.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-10\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-10.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-10.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-10.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-10.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-11\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-11.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-11.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-11.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-11.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-12\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-12.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-12.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-12.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-12.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-13\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-13.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-13.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-13.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-13.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-14\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-14.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-14.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-14.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-14.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-15\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-15.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-15.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-15.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-15.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-16\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-16.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-16.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-16.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-16.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-17\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-17.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-17.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-17.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-17.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-18\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-18.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-18.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-18.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-18.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-19\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-19.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-19.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-19.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-19.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-20\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-20.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-20.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-20.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-20.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-21\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-21.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-21.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-21.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-21.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-22\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-22.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-22.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-22.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-22.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-23\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-23.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-23.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-23.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-23.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-24\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-24.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-24.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-24.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-24.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-25\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-25.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-25.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-25.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-25.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-26\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-26.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-26.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-26.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-26.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-27\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-27.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-27.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-27.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-27.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-28\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-28.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-28.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-28.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-28.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-29\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-29.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-29.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-29.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-29.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-30\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-30.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-30.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-30.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-30.egr-bw_adjacent.bin 32 30 200 10 0.01 1
echo -e "input:toroid-wedge.mesh-M-4-idx-31\n"
./ispan ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-31.egr-fw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-31.egr-fw_adjacent.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-31.egr-bw_begin.bin ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-31.egr-bw_adjacent.bin 32 30 200 10 0.01 1
exit 0

