#!/bin/bash 
 clear
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-0.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-0.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-1.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-1.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-10.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-10.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-11.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-11.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-12.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-12.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-13.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-13.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-14.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-14.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-15.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-15.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-16.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-16.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-17.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-17.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-18.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-18.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-19.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-19.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-2.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-2.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-20.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-20.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-21.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-21.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-22.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-22.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-23.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-23.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-24.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-24.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-25.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-25.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-26.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-26.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-27.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-27.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-28.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-28.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-29.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-29.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-3.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-3.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-30.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-30.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-31.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-31.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-4.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-4.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-5.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-5.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-6.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-6.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-7.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-7.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-8.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-8.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-9.mtx ~/inputs/large_mesh_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-9.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-0.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-0.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-1.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-1.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-10.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-10.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-11.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-11.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-12.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-12.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-13.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-13.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-14.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-14.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-15.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-15.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-16.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-16.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-17.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-17.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-18.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-18.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-19.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-19.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-2.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-2.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-20.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-20.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-21.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-21.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-22.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-22.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-23.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-23.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-24.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-24.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-25.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-25.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-26.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-26.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-27.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-27.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-28.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-28.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-29.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-29.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-3.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-3.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-30.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-30.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-31.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-31.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-4.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-4.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-5.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-5.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-6.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-6.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-7.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-7.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-8.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-8.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-9.mtx ~/inputs/large_mesh_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-9.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/klein-bottle.mesh-M-4-idx-0.mtx ~/inputs/large_mesh_graphs/klein-bottle.mesh-M-4-idx-0.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/klein-bottle.mesh-M-4-idx-1.mtx ~/inputs/large_mesh_graphs/klein-bottle.mesh-M-4-idx-1.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/klein-bottle.mesh-M-4-idx-2.mtx ~/inputs/large_mesh_graphs/klein-bottle.mesh-M-4-idx-2.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/klein-bottle.mesh-M-4-idx-3.mtx ~/inputs/large_mesh_graphs/klein-bottle.mesh-M-4-idx-3.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/klein-bottle.mesh-M-4-idx-4.mtx ~/inputs/large_mesh_graphs/klein-bottle.mesh-M-4-idx-4.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/klein-bottle.mesh-M-4-idx-5.mtx ~/inputs/large_mesh_graphs/klein-bottle.mesh-M-4-idx-5.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/klein-bottle.mesh-M-4-idx-6.mtx ~/inputs/large_mesh_graphs/klein-bottle.mesh-M-4-idx-6.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/klein-bottle.mesh-M-4-idx-7.mtx ~/inputs/large_mesh_graphs/klein-bottle.mesh-M-4-idx-7.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/mobius-strip.mesh-M-4-idx-0.mtx ~/inputs/large_mesh_graphs/mobius-strip.mesh-M-4-idx-0.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/mobius-strip.mesh-M-4-idx-1.mtx ~/inputs/large_mesh_graphs/mobius-strip.mesh-M-4-idx-1.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/mobius-strip.mesh-M-4-idx-2.mtx ~/inputs/large_mesh_graphs/mobius-strip.mesh-M-4-idx-2.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/mobius-strip.mesh-M-4-idx-3.mtx ~/inputs/large_mesh_graphs/mobius-strip.mesh-M-4-idx-3.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/mobius-strip.mesh-M-4-idx-4.mtx ~/inputs/large_mesh_graphs/mobius-strip.mesh-M-4-idx-4.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/mobius-strip.mesh-M-4-idx-5.mtx ~/inputs/large_mesh_graphs/mobius-strip.mesh-M-4-idx-5.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/mobius-strip.mesh-M-4-idx-6.mtx ~/inputs/large_mesh_graphs/mobius-strip.mesh-M-4-idx-6.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/mobius-strip.mesh-M-4-idx-7.mtx ~/inputs/large_mesh_graphs/mobius-strip.mesh-M-4-idx-7.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-0.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-0.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-1.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-1.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-10.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-10.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-11.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-11.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-12.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-12.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-13.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-13.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-14.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-14.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-15.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-15.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-16.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-16.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-17.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-17.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-18.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-18.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-19.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-19.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-2.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-2.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-20.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-20.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-21.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-21.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-22.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-22.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-23.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-23.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-24.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-24.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-25.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-25.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-26.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-26.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-27.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-27.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-28.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-28.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-29.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-29.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-3.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-3.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-30.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-30.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-31.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-31.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-4.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-4.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-5.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-5.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-6.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-6.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-7.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-7.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-8.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-8.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-9.mtx ~/inputs/large_mesh_graphs/toroid-hex.mesh-M-4-idx-9.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-0.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-0.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-1.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-1.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-10.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-10.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-11.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-11.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-12.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-12.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-13.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-13.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-14.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-14.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-15.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-15.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-16.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-16.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-17.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-17.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-18.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-18.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-19.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-19.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-2.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-2.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-20.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-20.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-21.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-21.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-22.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-22.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-23.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-23.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-24.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-24.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-25.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-25.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-26.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-26.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-27.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-27.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-28.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-28.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-29.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-29.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-3.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-3.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-30.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-30.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-31.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-31.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-4.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-4.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-5.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-5.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-6.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-6.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-7.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-7.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-8.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-8.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-9.mtx ~/inputs/large_mesh_graphs/toroid-wedge.mesh-M-4-idx-9.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-0.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-0.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-1.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-1.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-10.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-10.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-11.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-11.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-12.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-12.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-13.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-13.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-14.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-14.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-15.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-15.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-16.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-16.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-17.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-17.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-18.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-18.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-19.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-19.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-2.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-2.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-20.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-20.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-21.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-21.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-22.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-22.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-23.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-23.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-24.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-24.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-25.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-25.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-26.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-26.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-27.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-27.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-28.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-28.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-3.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-3.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-4.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-4.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-5.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-5.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-6.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-6.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-7.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-7.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-8.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-8.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-9.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-9.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-0.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-0.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-1.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-1.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-10.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-10.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-11.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-11.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-12.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-12.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-13.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-13.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-14.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-14.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-15.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-15.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-16.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-16.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-17.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-17.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-18.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-18.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-19.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-19.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-2.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-2.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-20.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-20.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-21.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-21.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-22.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-22.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-23.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-23.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-24.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-24.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-25.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-25.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-26.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-26.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-27.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-27.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-28.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-28.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-29.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-29.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-3.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-3.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-30.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-30.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-31.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-31.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-4.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-4.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-5.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-5.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-6.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-6.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-7.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-7.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-8.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-8.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-9.mtx ~/inputs/large_mesh_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-9.txt
exit 0