#!/bin/bash 
 clear
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-0.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-0.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-1.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-1.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-10.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-10.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-11.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-11.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-12.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-12.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-13.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-13.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-14.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-14.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-15.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-15.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-16.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-16.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-17.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-17.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-18.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-18.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-19.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-19.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-2.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-2.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-20.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-20.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-21.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-21.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-22.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-22.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-23.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-23.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-24.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-24.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-25.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-25.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-26.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-26.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-27.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-27.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-28.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-28.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-29.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-29.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-3.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-3.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-30.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-30.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-31.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-31.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-4.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-4.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-5.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-5.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-6.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-6.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-7.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-7.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-8.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-8.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-sponge-tao4-r2.msh-M-4-idx-9.mtx cold-flow-sponge-tao4-r2.msh-M-4-idx-9.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-0.mtx cold-flow-spongezone3.c1.msh-M-4-idx-0.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-1.mtx cold-flow-spongezone3.c1.msh-M-4-idx-1.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-10.mtx cold-flow-spongezone3.c1.msh-M-4-idx-10.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-11.mtx cold-flow-spongezone3.c1.msh-M-4-idx-11.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-12.mtx cold-flow-spongezone3.c1.msh-M-4-idx-12.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-13.mtx cold-flow-spongezone3.c1.msh-M-4-idx-13.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-14.mtx cold-flow-spongezone3.c1.msh-M-4-idx-14.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-15.mtx cold-flow-spongezone3.c1.msh-M-4-idx-15.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-16.mtx cold-flow-spongezone3.c1.msh-M-4-idx-16.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-17.mtx cold-flow-spongezone3.c1.msh-M-4-idx-17.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-18.mtx cold-flow-spongezone3.c1.msh-M-4-idx-18.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-19.mtx cold-flow-spongezone3.c1.msh-M-4-idx-19.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-2.mtx cold-flow-spongezone3.c1.msh-M-4-idx-2.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-20.mtx cold-flow-spongezone3.c1.msh-M-4-idx-20.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-21.mtx cold-flow-spongezone3.c1.msh-M-4-idx-21.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-22.mtx cold-flow-spongezone3.c1.msh-M-4-idx-22.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-23.mtx cold-flow-spongezone3.c1.msh-M-4-idx-23.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-24.mtx cold-flow-spongezone3.c1.msh-M-4-idx-24.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-25.mtx cold-flow-spongezone3.c1.msh-M-4-idx-25.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-26.mtx cold-flow-spongezone3.c1.msh-M-4-idx-26.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-27.mtx cold-flow-spongezone3.c1.msh-M-4-idx-27.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-28.mtx cold-flow-spongezone3.c1.msh-M-4-idx-28.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-29.mtx cold-flow-spongezone3.c1.msh-M-4-idx-29.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-3.mtx cold-flow-spongezone3.c1.msh-M-4-idx-3.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-30.mtx cold-flow-spongezone3.c1.msh-M-4-idx-30.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-31.mtx cold-flow-spongezone3.c1.msh-M-4-idx-31.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-4.mtx cold-flow-spongezone3.c1.msh-M-4-idx-4.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-5.mtx cold-flow-spongezone3.c1.msh-M-4-idx-5.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-6.mtx cold-flow-spongezone3.c1.msh-M-4-idx-6.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-7.mtx cold-flow-spongezone3.c1.msh-M-4-idx-7.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-8.mtx cold-flow-spongezone3.c1.msh-M-4-idx-8.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/cold-flow-spongezone3.c1.msh-M-4-idx-9.mtx cold-flow-spongezone3.c1.msh-M-4-idx-9.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/klein-bottle.mesh-M-4-idx-0.mtx klein-bottle.mesh-M-4-idx-0.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/klein-bottle.mesh-M-4-idx-1.mtx klein-bottle.mesh-M-4-idx-1.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/klein-bottle.mesh-M-4-idx-2.mtx klein-bottle.mesh-M-4-idx-2.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/klein-bottle.mesh-M-4-idx-3.mtx klein-bottle.mesh-M-4-idx-3.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/klein-bottle.mesh-M-4-idx-4.mtx klein-bottle.mesh-M-4-idx-4.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/klein-bottle.mesh-M-4-idx-5.mtx klein-bottle.mesh-M-4-idx-5.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/klein-bottle.mesh-M-4-idx-6.mtx klein-bottle.mesh-M-4-idx-6.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/klein-bottle.mesh-M-4-idx-7.mtx klein-bottle.mesh-M-4-idx-7.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/mobius-strip.mesh-M-4-idx-0.mtx mobius-strip.mesh-M-4-idx-0.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/mobius-strip.mesh-M-4-idx-1.mtx mobius-strip.mesh-M-4-idx-1.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/mobius-strip.mesh-M-4-idx-2.mtx mobius-strip.mesh-M-4-idx-2.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/mobius-strip.mesh-M-4-idx-3.mtx mobius-strip.mesh-M-4-idx-3.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/mobius-strip.mesh-M-4-idx-4.mtx mobius-strip.mesh-M-4-idx-4.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/mobius-strip.mesh-M-4-idx-5.mtx mobius-strip.mesh-M-4-idx-5.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/mobius-strip.mesh-M-4-idx-6.mtx mobius-strip.mesh-M-4-idx-6.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/mobius-strip.mesh-M-4-idx-7.mtx mobius-strip.mesh-M-4-idx-7.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-0.mtx toroid-hex.mesh-M-4-idx-0.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-1.mtx toroid-hex.mesh-M-4-idx-1.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-10.mtx toroid-hex.mesh-M-4-idx-10.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-11.mtx toroid-hex.mesh-M-4-idx-11.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-12.mtx toroid-hex.mesh-M-4-idx-12.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-13.mtx toroid-hex.mesh-M-4-idx-13.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-14.mtx toroid-hex.mesh-M-4-idx-14.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-15.mtx toroid-hex.mesh-M-4-idx-15.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-16.mtx toroid-hex.mesh-M-4-idx-16.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-17.mtx toroid-hex.mesh-M-4-idx-17.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-18.mtx toroid-hex.mesh-M-4-idx-18.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-19.mtx toroid-hex.mesh-M-4-idx-19.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-2.mtx toroid-hex.mesh-M-4-idx-2.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-20.mtx toroid-hex.mesh-M-4-idx-20.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-21.mtx toroid-hex.mesh-M-4-idx-21.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-22.mtx toroid-hex.mesh-M-4-idx-22.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-23.mtx toroid-hex.mesh-M-4-idx-23.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-24.mtx toroid-hex.mesh-M-4-idx-24.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-25.mtx toroid-hex.mesh-M-4-idx-25.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-26.mtx toroid-hex.mesh-M-4-idx-26.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-27.mtx toroid-hex.mesh-M-4-idx-27.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-28.mtx toroid-hex.mesh-M-4-idx-28.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-29.mtx toroid-hex.mesh-M-4-idx-29.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-3.mtx toroid-hex.mesh-M-4-idx-3.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-30.mtx toroid-hex.mesh-M-4-idx-30.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-31.mtx toroid-hex.mesh-M-4-idx-31.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-4.mtx toroid-hex.mesh-M-4-idx-4.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-5.mtx toroid-hex.mesh-M-4-idx-5.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-6.mtx toroid-hex.mesh-M-4-idx-6.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-7.mtx toroid-hex.mesh-M-4-idx-7.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-8.mtx toroid-hex.mesh-M-4-idx-8.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-hex.mesh-M-4-idx-9.mtx toroid-hex.mesh-M-4-idx-9.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-0.mtx toroid-wedge.mesh-M-4-idx-0.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-1.mtx toroid-wedge.mesh-M-4-idx-1.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-10.mtx toroid-wedge.mesh-M-4-idx-10.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-11.mtx toroid-wedge.mesh-M-4-idx-11.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-12.mtx toroid-wedge.mesh-M-4-idx-12.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-13.mtx toroid-wedge.mesh-M-4-idx-13.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-14.mtx toroid-wedge.mesh-M-4-idx-14.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-15.mtx toroid-wedge.mesh-M-4-idx-15.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-16.mtx toroid-wedge.mesh-M-4-idx-16.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-17.mtx toroid-wedge.mesh-M-4-idx-17.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-18.mtx toroid-wedge.mesh-M-4-idx-18.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-19.mtx toroid-wedge.mesh-M-4-idx-19.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-2.mtx toroid-wedge.mesh-M-4-idx-2.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-20.mtx toroid-wedge.mesh-M-4-idx-20.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-21.mtx toroid-wedge.mesh-M-4-idx-21.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-22.mtx toroid-wedge.mesh-M-4-idx-22.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-23.mtx toroid-wedge.mesh-M-4-idx-23.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-24.mtx toroid-wedge.mesh-M-4-idx-24.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-25.mtx toroid-wedge.mesh-M-4-idx-25.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-26.mtx toroid-wedge.mesh-M-4-idx-26.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-27.mtx toroid-wedge.mesh-M-4-idx-27.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-28.mtx toroid-wedge.mesh-M-4-idx-28.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-29.mtx toroid-wedge.mesh-M-4-idx-29.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-3.mtx toroid-wedge.mesh-M-4-idx-3.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-30.mtx toroid-wedge.mesh-M-4-idx-30.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-31.mtx toroid-wedge.mesh-M-4-idx-31.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-4.mtx toroid-wedge.mesh-M-4-idx-4.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-5.mtx toroid-wedge.mesh-M-4-idx-5.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-6.mtx toroid-wedge.mesh-M-4-idx-6.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-7.mtx toroid-wedge.mesh-M-4-idx-7.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-8.mtx toroid-wedge.mesh-M-4-idx-8.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/toroid-wedge.mesh-M-4-idx-9.mtx toroid-wedge.mesh-M-4-idx-9.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-0.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-0.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-1.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-1.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-10.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-10.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-11.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-11.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-12.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-12.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-13.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-13.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-14.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-14.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-15.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-15.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-16.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-16.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-17.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-17.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-18.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-18.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-19.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-19.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-2.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-2.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-20.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-20.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-21.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-21.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-22.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-22.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-23.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-23.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-24.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-24.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-25.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-25.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-26.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-26.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-27.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-27.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-28.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-28.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-3.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-3.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-4.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-4.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-5.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-5.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-6.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-6.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-7.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-7.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-8.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-8.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s3-r4-p.mesh-M-4-idx-9.mtx twist-hex-o3-s3-r4-p.mesh-M-4-idx-9.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-0.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-0.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-1.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-1.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-10.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-10.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-11.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-11.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-12.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-12.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-13.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-13.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-14.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-14.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-15.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-15.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-16.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-16.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-17.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-17.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-18.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-18.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-19.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-19.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-2.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-2.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-20.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-20.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-21.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-21.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-22.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-22.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-23.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-23.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-24.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-24.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-25.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-25.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-26.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-26.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-27.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-27.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-28.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-28.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-29.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-29.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-3.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-3.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-30.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-30.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-31.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-31.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-4.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-4.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-5.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-5.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-6.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-6.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-7.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-7.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-8.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-8.txt
./mtx2el-iSpan ~/inputs/mtx_graphs/twist-hex-o3-s6-r4-p.mesh-M-4-idx-9.mtx twist-hex-o3-s6-r4-p.mesh-M-4-idx-9.txt
exit 0

