#!/bin/bash 
 clear
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-0.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-0.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-0.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-0.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-1.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-1.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-1.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-1.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-2.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-2.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-2.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-2.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-3.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-3.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-3.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-3.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-4.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-4.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-4.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-4.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-5.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-5.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-5.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-5.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-6.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-6.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-6.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-6.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-7.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-7.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-7.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-7.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-3.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-3.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-3.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-3.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-8.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-8.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-8.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-8.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-9.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-9.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-9.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-9.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-10.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-10.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-10.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-10.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-11.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-11.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-11.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-11.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-12.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-12.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-12.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-12.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-13.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-13.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-13.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-13.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-14.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-14.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-14.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-14.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-15.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-15.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-15.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-15.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-16.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-16.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-16.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-16.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-17.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-17.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-17.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-17.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-18.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-18.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-18.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-18.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-19.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-19.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-19.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-19.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-20.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-20.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-20.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-20.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-21.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-21.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-21.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-21.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-22.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-22.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-22.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-22.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-23.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-23.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-23.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-23.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-24.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-24.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-24.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-24.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-25.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-25.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-25.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-25.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-26.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-26.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-26.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-26.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-27.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-27.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-27.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-27.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-28.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-28.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/beam-hex.mesh-M-4-idx-28.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/beam-hex.mesh-M-4-idx-28.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/star.mesh-M-4-idx-0.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-0.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/star.mesh-M-4-idx-0.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-0.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/star.mesh-M-4-idx-1.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-1.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/star.mesh-M-4-idx-1.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-1.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/star.mesh-M-4-idx-2.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-2.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/star.mesh-M-4-idx-2.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-2.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/star.mesh-M-4-idx-3.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-3.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/star.mesh-M-4-idx-3.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-3.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/star.mesh-M-4-idx-4.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-4.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/star.mesh-M-4-idx-4.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-4.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/star.mesh-M-4-idx-5.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-5.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/star.mesh-M-4-idx-5.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-5.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/star.mesh-M-4-idx-6.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-6.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/star.mesh-M-4-idx-6.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-6.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/star.mesh-M-4-idx-7.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-7.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/star.mesh-M-4-idx-7.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/star.mesh-M-4-idx-7.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-0.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-0.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-0.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-0.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-10.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-10.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-10.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-10.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-11.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-11.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-11.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-11.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-12.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-12.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-12.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-12.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-13.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-13.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-13.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-13.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-14.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-14.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-14.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-14.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-15.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-15.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-15.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-15.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-16.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-16.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-16.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-16.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-17.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-17.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-17.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-17.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-18.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-18.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-18.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-18.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-19.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-19.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-19.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-19.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-1.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-1.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-1.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-1.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-20.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-20.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-20.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-20.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-21.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-21.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-21.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-21.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-22.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-22.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-22.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-22.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-23.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-23.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-23.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-23.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-24.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-24.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-24.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-24.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-25.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-25.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-25.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-25.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-26.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-26.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-26.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-26.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-27.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-27.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-27.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-27.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-28.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-28.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-28.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-28.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-29.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-29.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-29.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-29.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-2.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-2.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-2.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-2.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-30.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-30.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-30.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-30.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-31.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-31.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-31.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-31.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-3.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-3.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-3.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-3.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-4.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-4.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-4.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-4.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-5.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-5.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-5.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-5.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-6.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-6.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-6.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-6.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-7.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-7.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-7.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-7.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-8.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-8.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-8.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-8.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-9.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-9.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-sponge-tao4-r2.msh-M-4-idx-9.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-sponge-tao4-r2.msh-M-4-idx-9.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-0.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-0.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-0.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-0.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-10.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-10.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-10.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-10.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-11.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-11.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-11.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-11.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-12.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-12.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-12.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-12.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-13.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-13.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-13.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-13.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-14.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-14.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-14.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-14.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-15.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-15.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-15.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-15.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-16.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-16.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-16.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-16.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-17.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-17.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-17.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-17.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-18.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-18.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-18.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-18.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-19.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-19.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-19.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-19.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-1.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-1.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-1.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-1.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-20.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-20.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-20.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-20.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-21.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-21.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-21.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-21.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-22.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-22.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-22.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-22.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-23.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-23.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-23.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-23.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-24.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-24.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-24.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-24.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-25.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-25.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-25.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-25.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-26.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-26.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-26.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-26.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-27.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-27.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-27.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-27.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-28.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-28.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-28.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-28.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-29.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-29.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-29.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-29.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-2.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-2.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-2.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-2.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-30.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-30.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-30.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-30.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-31.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-31.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-31.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-31.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-3.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-3.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-3.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-3.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-4.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-4.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-4.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-4.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-5.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-5.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-5.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-5.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-6.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-6.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-6.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-6.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-7.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-7.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-7.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-7.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-8.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-8.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-8.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-8.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-9.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-9.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/cold-flow-spongezone3.c1.msh-M-4-idx-9.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/cold-flow-spongezone3.c1.msh-M-4-idx-9.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-0.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-0.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-0.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-0.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-1.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-1.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-1.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-1.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-2.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-2.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-2.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-2.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-3.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-3.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-3.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-3.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-4.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-4.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-4.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-4.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-5.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-5.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-5.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-5.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-6.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-6.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-6.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-6.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-7.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-7.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-7.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-7.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-8.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-8.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-8.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-8.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-9.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-9.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-9.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-9.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-10.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-10.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-10.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-10.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-11.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-11.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-11.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-11.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-12.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-12.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-12.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-12.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-13.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-13.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-13.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-13.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-14.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-14.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-14.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-14.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-15.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-15.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-15.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-15.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-16.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-16.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-16.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-16.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-17.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-17.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-17.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-17.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-18.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-18.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-18.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-18.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-19.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-19.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-19.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-19.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-20.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-20.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-20.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-20.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-21.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-21.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-21.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-21.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-22.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-22.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-22.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-22.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-23.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-23.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-23.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-23.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-24.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-24.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-24.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-24.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-25.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-25.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-25.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-25.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-26.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-26.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-26.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-26.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-27.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-27.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-27.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-27.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-28.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-28.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-28.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-28.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-29.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-29.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-29.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-29.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-30.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-30.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-30.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-30.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-31.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-31.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-hex.mesh-M-4-idx-31.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-hex.mesh-M-4-idx-31.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-0.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-0.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-0.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-0.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-1.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-1.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-1.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-1.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-2.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-2.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-2.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-2.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-3.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-3.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-3.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-3.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-4.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-4.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-4.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-4.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-5.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-5.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-5.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-5.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-6.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-6.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-6.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-6.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-7.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-7.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-7.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-7.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-8.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-8.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-8.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-8.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-9.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-9.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-9.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-9.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-10.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-10.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-10.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-10.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-11.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-11.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-11.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-11.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-12.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-12.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-12.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-12.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-13.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-13.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-13.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-13.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-14.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-14.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-14.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-14.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-15.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-15.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-15.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-15.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-16.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-16.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-16.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-16.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-17.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-17.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-17.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-17.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-18.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-18.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-18.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-18.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-19.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-19.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-19.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-19.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-20.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-20.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-20.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-20.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-21.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-21.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-21.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-21.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-22.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-22.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-22.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-22.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-23.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-23.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-23.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-23.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-24.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-24.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-24.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-24.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-25.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-25.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-25.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-25.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-26.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-26.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-26.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-26.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-27.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-27.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-27.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-27.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-28.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-28.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-28.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-28.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-29.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-29.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-29.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-29.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-30.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-30.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-30.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-30.egr-
./txt_to_bin_fw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-31.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-31.egr-
./txt_to_bin_bw ~/inputs/iSpan_Graphs/small_mesh_graph/toroid-wedge.mesh-M-4-idx-31.txt ~/inputs/iSpan_Graphs/small_mesh_graph/ispan/toroid-wedge.mesh-M-4-idx-31.egr-
exit 0
=
